### ISSUE TITLE
Why that!?

### ISSUE THREAD

**Issue by iamousseni** [Zexal0807/Zexarel#1]
Non capisco perchè nella classe ZLogger non abbia esteso o per lo meno incluso la classe Log nel file ZLogger. Anche perchè da come vedo ZLogger dipende dalla classe Log e senza tale non potrebbe funzionare.

**Comment by Zexal0807** [comment]
ZLog è una classe che gestisce l'oggetto log
ZLogger è la classe che scrive su file un log
